### ISSUE TITLE
Unsupported config option for services service: 'geth'

### ISSUE THREAD

**Issue by nisang** [DaoCloud/dao-chain#2]
Run:
$:docker-compose up -d

Question:
Unsupported config option for services service: 'geth'

INFO:
system:CoreOS
docker:version 1.11.2

Request:
是否还需要安装geth才能正常启动

**Comment by Windfarer** [comment]
检查一下docker-compose的版本，可能需要升级

**Comment by Revolution1** [comment]
docker 也可以升级一下
