### ISSUE TITLE
初始化钱包后还是会经常弹出选择组织

### ISSUE THREAD

**Issue by yourtion** [DaoCloud/dao-chain#3]
钱包已经初始化了，也可以挖矿，如下图：

![screen shot 2016-12-07 at 9 47 15 pm](https://cloud.githubusercontent.com/assets/1475301/20970180/451d081a-bcc7-11e6-94f6-6eb3c16254b8.png)

![screen shot 2016-12-07 at 9 47 24 pm](https://cloud.githubusercontent.com/assets/1475301/20970182/46506920-bcc7-11e6-8e1a-4d676c59de4e.png)

但是经常弹出下图：

![screen shot 2016-12-07 at 9 49 47 pm](https://cloud.githubusercontent.com/assets/1475301/20970189/50d5c232-bcc7-11e6-8c00-bda45efed31e.png)

这样是已经工作正常了，只是页面有bug，还是我初始化和加入组织的方法有问题？

**Comment by Revolution1** [comment]
好像是你的地址和组织没有绑定成功，前端没有捕捉到这个错误。现在的 Daochain 在流程上有些问题。现在的解决方法就是你手动备份一下你原来的 keystore 然后重新创建容器，重新创建一个钱包，然后导入keystore把原来挖出来的币转入到新的钱包里。。。。。。。。
或者你可以看一下 app/daocloud.py 手动 call daohub的api，绑定你现在的钱包地址

**Comment by Revolution1** [comment]
应该是你的 daocloud 账户名下没有 daocloud 组织，内测版本默认是只支持有组织的用户的。当然你可以用我上面说的方法绕过

**Comment by yourtion** [comment]
好吧，应该是我的 daocloud 账户名下没有 daocloud 组织。我试试看，怎么样确定我已经成功绑定组织？就是不弹出我那个选择组织的么？

**Comment by Revolution1** [comment]
sorry 仔细想了一下好像是没法绕过的，除非你改一下代码重新打镜像。。。。。

把：
```
    @property
    def orgs(self):
        """
        :rtype: list(dict)
        """
        orgs = []
        for t in self.token_info['user']['tenants']:
            if t['is_org']:
                orgs.append(t)
        return orgs
```

改成:
```
    @property
    def orgs(self):
        """
        :rtype: list(dict)
        """
        return self.token_info['user']['tenants']
```

然后重新打包一下镜像，做一个你自己的“魔改版”。。。。

**Comment by yourtion** [comment]
我试试看

**Comment by Revolution1** [comment]
记得备份 keystore

**Comment by yourtion** [comment]
@Revolution1 我进容器改了，不出现那个组织界面了好像，但是我还是要手动去绑定组织？

**Comment by Revolution1** [comment]
@yourtion 是的，需要手动绑一下
